/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package daisy.static_architecture.elements.views;

import daisy.static_architecture.elements.MatchingUnit;
import daisy.static_architecture.elements.actions.AddInputAction;
import daisy.static_architecture.elements.actions.AddInstructionAction;
import daisy.static_architecture.elements.implementation.StaticMatchingUnit;
import java.awt.Point;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author Wittman
 */
public class MatchingUnitView extends ElementView{

    private StaticMatchingUnit matchingUnit;
    
    /**
     * Creates new form MatchingUnitView
     * @param MU
     */
    public MatchingUnitView(StaticMatchingUnit MU) {
        super(MU);
        matchingUnit = MU; 
        initElementVertexes();
        initComponents();
        this.setSize(this.preferredSize());
    }
    
    
    
    @Override
    protected void initElementVertexes() {
        addPin(new Point(5, 100));
        addPin(new Point(240, 100));
    }
    
    
    @Override
    public JPopupMenu getPopupMenu() {
        if(popupMenu == null){
            popupMenu = super.getPopupMenu();
            
            JMenuItem menuItem = new JMenuItem("Add token");
            menuItem.addActionListener(new AddInstructionAction(matchingUnit));
            popupMenu.add(menuItem);
        }
        return popupMenu;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    @Override
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

     
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(250, 200));

        jLabel1.setText("Matching Unit");

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(matchingUnit);
        jTable2.setToolTipText("");
        jTable2.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
