package daisy.static_architecture.parser;


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 06 14:25:04 EET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 9;
  public static final int IDENT = 8;
  public static final int COLON = 6;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int ARROW = 7;
  public static final int REAL = 10;
  public static final int error = 1;
  public static final int COMMA = 3;
  public static final int LEFT_BRKT = 4;
  public static final int RT_BRKT = 5;
}

